# Welcome to Jekyll!    sudo bundle exec jekyll serve
# Always update ruby gems - gem update && gem cleanup
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Donald
subtitle: Nowels
email: djnowels11@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a Front-End Developer. A conscientious, fast learner
  offering the ability to assess an organization’s needs and
  create a complementary, robust web presence. I am both
  driven and self-motivated, and I am constantly
  experimenting with new technologies and techniques.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
street_address: 1234 Somewhere Road
city: Philadelphia
state: PA
zip_code: 55555
country: United States of America

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/dln5057
linkedin_url: https://www.linkedin.com/in/donald-nowels/
pinterest_url:
slack_url:
twitter_url:
email_url: djnowels11@gmail.com

# Build settings
markdown: kramdown
theme: forty_jekyll_theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
